name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Publish Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: poketwo
          password: ${{ secrets.GHCR_PAT }}
          registry: ghcr.io
          image_name: webhook-server
          image_tag: latest,${{ github.sha }}
